apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
{{- with .Values.service.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if (eq .Values.service.type "ExternalName") }}
  externalName: {{ .Values.service.externalName }}
  {{- end }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if (and (eq .Values.service.type "ClusterIP") (eq .Values.service.headless true)) }}
  clusterIP: None
  {{- end }}
{{- if (not (eq .Values.service.type "ExternalName") ) }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPorts.http }}
      {{- if (not (empty .Values.service.nodePorts.http)) }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
    - name: https
      port: {{ .Values.service.ports.https }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPorts.https }}
      {{- if (not (empty .Values.service.nodePorts.https)) }}
      nodePort: {{ .Values.service.nodePorts.https }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-headless
  labels:
{{ include "labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http-in
    - name: https
      port: 443
      protocol: TCP
      targetPort: https-in
  selector:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-internal
  labels:
{{ include "labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    # - name: http
    #   port: 80
    #   protocol: TCP
    #   targetPort: http-in
    # - name: https
    #   port: 443
    #   protocol: TCP
    #   targetPort: https-in
    - name: stats
      port: 8080
      protocol: TCP
      targetPort: stats
  selector:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
